global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: "codelab-monitor"
rule_files:
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: docker
    static_configs:
      - targets: ["localhost:9323"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:8080"]